Hw13 calendar grpc gateway
dimonk33/kdv_hw_otus pull request #14
Opened 2023-04-16 13:04 UTC by dimonk33

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-04-17 16:09 UTC, dshemin requested changes

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +generate:
Критично:

> добавить в Makefile команду `generate`; `make generate` - вызывает `go generate`, которая в свою очередь
генерирует код GRPC сервера на основе Protobuf спецификаций;

Нужно использовать go:generate

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +    Event data = 1;
Важно:

В некоторых сообщениях у вас поле с маленькой, а в других с большой. Советую придерживаться одного стиля.

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		if err := grpcServer.Stop(ctx); err != nil {
Важно:

А где закрывается HTTP сервер?

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	if ev.OwnUserID == 0 {
Важно:

Согласно протофайлу у нас тут могут быть отрицательные числа. На это тоже надо сделать проверку.

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	if ev.ID == 0 {
Важно:

Согласно протофайлу у нас тут могут быть отрицательные числа. На это тоже надо сделать проверку.

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	if ev.OwnUserID == 0 {
Важно:

Согласно протофайлу у нас тут могут быть отрицательные числа. На это тоже надо сделать проверку.

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	if req.ID == 0 {
Важно:

Согласно протофайлу у нас тут могут быть отрицательные числа. На это тоже надо сделать проверку.

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	if ev == nil {
Важно:

Обратите внимание на сгенерённый код. Там есть методы для получения значений и они учитывают ситуацию когда сама структура может быть nil

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	data, err := s.worker.ListEventOnDate(ctx, int(req.Year), int(req.Month), int(req.Day))
Важно:

Все эти поля могут быть отрицательными.

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	res := &gen.CreateEventResult{}
Важно:

Мы создаём структуру, которая может быть не нужна если запрос не пройдёт валидацию.

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server_test.go
> +				require.NotNil(t, err)
Важно:

Лучше require.Error

2023-04-17 16:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +	Logger Logger
Важно:

Зачем тут логер сделан публичым?

2023-04-17 19:34 UTC, dimonk33 commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +	Logger Logger
Хотел использовать для GRPC и забыл вернуть

2023-04-18 05:27 UTC, dshemin approved these changes

2023-04-18 06:36 UTC, merged